### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by Oguzhanercan** [csyxwei/MasterWeaver#1]
Hi, is there any certain date for release?

**Comment by csyxwei** [comment]
Thank you for your interest! We will release the code in two weeks.

**Comment by Oguzhanercan** [comment]
Thanks

**Comment by Oguzhanercan** [comment]
It has been 2 months :/

**Comment by csyxwei** [comment]
Hi, sorry for the late release. We have released our code and model.

**Comment by Oguzhanercan** [comment]
thanks, lets try it..
